### PR TITLE
Convert Json, Reflection tests files + correct of Misc tests file

### PR DESCRIPTION
**Pull request by EdouardM**
Hello Alfonso, 

I converted the tests files Json and Reflection to make them work with Expecto on dotnet std 2.0. 

Regarding  Json I added a reference to the project Fable.JsonConverter in the fsproj file. I also added a dependency on Newtonsoft.Json package. 

I also modified the Misc tests file to correct al the compilation errors. 

I hope this will help. If you any request please feel free to ask. 

Regards;
Edouard

### CODE REVIEW

**Comment by EdouardM** [comment]
I am fine to keep the PR on hold. 
I saw you asked for some help on other part of Fable 2. I am going to look for something I can do.

**Comment by alfonsogarciacaro** [comment]
Sorry @EdouardM. If you don't mind I'm closing this PR because finally we'll be moving JSON (de)serialization to other libraries like Fable.SimpleJson or Thoth.Json so we don't need the tests.

But I already copied manually the converted Misc and Reflection tests, so your work has indeed been very helpful. Thanks for it!
