### ISSUE TITLE
Error when building on clean Windows 10

### ISSUE THREAD

**Issue by tpetricek** [fable-compiler/Fable#405]
### Description

I finally updated to Windows 10, but now I'm getting the following error when I run `build MochaTest`:

```
> tsc "fable-core.ts" "--target" "ES2015" "--declaration"

CWD: src/fable/Fable.Core/npm
cmd /C npm run babel -- fable-core.js -o commonjs.js --compact=false

> fable-core@0.5.5 babel C:\tomas\public\fsprojects\Fable\src\fable\Fable.Core\npm
> babel "fable-core.js" "-o" "commonjs.js" "--compact=false"

Error: Cannot find module '../tokenizer'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\tomas\public\fsprojects\Fable\src\fable\Fable.Core\npm\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-function-name\node_modules\babel-helper-function-name\node_modules\babel-traverse\node_modules\babylon\lib\parser\index.js:36:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Programs\\Development\\Node\\node.exe" "C:\\Programs\\Development\\Node\\node_modules\\npm\\bin\\npm-cli.js" "run" "babel" "--" "fable-core.js" "-o" "commonjs.js" "--compact=false"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! fable-core@0.5.5 babel: `babel "fable-core.js" "-o" "commonjs.js" "--compact=false"`
npm ERR! Exit status 1
npm ERR!
```

### Related information 

 - Windows 10
 - Latest `master` version of Fable
 - I installed node 6.5.0, so perhaps I should have instead installed the version 4.something?

**Comment by alfonsogarciacaro** [comment]
Interesting, I tried running the build in AppVeyor with node 6.5.0 and it worked: https://github.com/fable-compiler/Fable/commit/b4fdb5f6d98e1117c74dae159de82146193a440b

Does this only happen with `MochaTest` target? It should be the same with the default target though as this command is issued in `FableCoreRelease` step.

**Comment by alfonsogarciacaro** [comment]
Maybe you can try deleting `src/fable/Fable.Core/npm/node_modules` for a new clean npm packages install?

**Comment by tpetricek** [comment]
Doh! 💚 That was it.
