### ISSUE TITLE
Cannot find replacement for Fable.Import.Node.child_process_types.Globals.spawn

### ISSUE THREAD

**Issue by flypixel** [fable-compiler/Fable#577]
### Description

Hello
Starting from **0.7 version** of fable compiler, I can't compile ionide-vscode-paket. When try to build project, it breaks with error: 

> _Cannot find replacement for Fable.Import.Node.child_process_types.Globals.spawn_

But if I try to compile with version <= 0.6.15, it's compiled without errors.
For both of scenarios I used Fable.Core with the last version (0.7.11).
Everything happened on Ubuntu 16.04 

### Expected behavior

Successful compilation of ionide-vscode-paket (master) project. The real problem is with ionide-vscode-helpers (master) in Helpers.fs, _spawn_ function.

### Actual behavior

"_Cannot find replacement for Fable.Import.Node.child_process_types.Globals.spawn_" compilation error occurred

### Known workarounds

Use fable-compiler version <= 0.6.15

### Related information 

* Fable Compiler Version  >= 0.7.6
* Fable Core Version 0.7.11
* Mono Version 4.8.0
* Operating system: Ubuntu 16.04

**Comment by alfonsogarciacaro** [comment]
Hmm, seems Node bindings need to be updated. For now, I just added a hack to make them work with Fable 0.7. I will soon publish fable-compiler 0.7.17, can you please give it a try?

**Comment by flypixel** [comment]
It works great, thank you
