### ISSUE TITLE
Compile error 1.1.12 - Method not found: 'Fable.AST.Fable.Expr Fable.AST.Fable.Util.makeEqOp ...

### ISSUE THREAD

**Issue by chadunit** [fable-compiler/Fable#1080]
### Description

I have a project that is getting a compilation error under 1.1.12, but compiles successfully under 1.1.11. The error appears to happen on the first source file attempted and doesn't seem to point to any particular line in my code.

### Repro code

Edit: See followup comment below for repro steps and error message.

### Expected and actual results

Edit: See followup comment below for repro steps and error message.

### Related information

* Fable version (`dotnet fable --version`): 1.1.12
* Dotnet version: 1.0.4
* Operating system: Windows 10

**Comment by chadunit** [comment]
This repros with Fable.Elmish.React.

Repro steps using the template:
```
dotnet new -i Fable.Template.Elmish.React::*
dotnet new fable-elmish-react -n testreact
cd .\testreact\
yarn install
dotnet restore
dotnet fable yarn-run build
```

At this point compile is successful because dotnet-fable version in template is 1.1.7.

Now edit `paket.dependencies` and specify `clitool dotnet-fable 1.1.11`, then:

```
.\.paket\paket.exe install
dotnet restore
dotnet fable yarn-run build
```

Confirm compile still works on 1.1.11.

Now edit `paket.dependencies` and specify `clitool dotnet-fable 1.1.12`, then:

```
.\.paket\paket.exe install
dotnet restore
dotnet fable yarn-run build
```

Compile now fails on 1.1.12.

```
C:\src\GameTest2.git\testreact [master ≡ +11 ~8 -1 !]> dotnet fable yarn-run build
Fable daemon started on port 61225
CWD: C:\src\GameTest2.git\testreact
cmd /C yarn run build
yarn run v0.24.6
$ webpack -p
Bundling for production...
Parsing ./testreact.fsproj...
fable: Compiled testreact.fsproj
ERROR: Method not found: 'Fable.AST.Fable.Expr Fable.AST.Fable.Util.makeEqOp(Microsoft.FSharp.Core.FSharpOption`1<Fable.SourceLocation>, Microsoft.FSharp.Collections.FSharpList`1<Fable.AST.Fable.Expr>, Fable.AST.BinaryOperator)'. (C:/src/GameTest2.git/testreact/src/App.fs)
   at Fable.FSharp2Fable.Compiler.transformExpr(IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.transformDeclarations@1162-1.Invoke(FSharpImplementationFileDeclaration decl)
   at Microsoft.FSharp.Collections.ListModule.loop@219-29[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
   at Fable.FSharp2Fable.Compiler.transformDeclarations(IFableCompiler com, Context ctx, FSharpList`1 decls)
   at Fable.FSharp2Fable.Compiler.transformFile(ICompiler com, ICompilerState state, FSharpCheckProjectResults checkedProject, String fileName)
Hash: d5ff76fdac227139333f
Version: webpack 2.6.1
Time: 8132ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  1.15 kB       0  [emitted]  main
bundle.js.map  7.64 kB       0  [emitted]  main
   [0] ./src/App.fs 430 bytes {0} [built] [failed] [1 error]
   [1] ./testreact.fsproj 29 bytes {0} [built]

ERROR in ./src/App.fs
Module build failed: Error: Method not found: 'Fable.AST.Fable.Expr Fable.AST.Fable.Util.makeEqOp(Microsoft.FSharp.Core.FSharpOption`1<Fable.SourceLocation>, Microsoft.FSharp.Collections.FSharpList`1<Fable.AST.Fable.Expr>, Fable.AST.BinaryOperator)'. (C:/src/GameTest2.git/testreact/src/App.fs)
    at tryLoadCache.then.then.err (C:\src\GameTest2.git\testreact\node_modules\fable-loader\index.js:130:22)
 @ ./testreact.fsproj 1:0-29
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Closing Fable daemon...
```

**Comment by alfonsogarciacaro** [comment]
Sorry, this is the decision to split Fable in three packages haunting me. I did a small refactoring in Fable.Core and forgot to publish it. Can you please try with dotnet-fable 1.1.14?

**Comment by chadunit** [comment]
Yes, it works with everything updated to latest, thanks!

**Comment by alfonsogarciacaro** [comment]
Thanks to you for the report!
