### ISSUE TITLE
Support applicatives within computation expressions using and! keywork

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2049]
### Description

Support applicatives within computation expressions using and! keywork

### Repro code
```fs
module App

let createAsync a = async { return a }

let value = async {
    let! a = createAsync 1
    and! b = createAsync 2
    return a + b
}
```

### Expected and actual results

Expected: It compiles and works correctly
Actual: doesn't compile

**Comment by ncave** [comment]
@Zaid-Ajaj I'm getting the following error when trying to reproduce on .NET Core 3.1.201:
```error FS1141: Identifiers followed by '!' are reserved for future use```

**Comment by ncave** [comment]
@Zaid-Ajaj I don't see the async builder implementing the new methods yet, so the repro above is not compiling on .NET either, at least for me.

But this works with latest Fable (2.8.4), as long as you have `<LangVersion>preview</LangVersion>` in your project file:
```fs
module App

type Applicative() =
    member x.MergeSources(a : option<'a>, b : option<'b>) =
        (a,b) ||> Option.map2 (fun a b -> (a,b))
    member x.Bind(m : option<'a>, mapping : 'a -> 'b) : option<'b> =
        m |> Option.map mapping
    member x.Return v = v

let app = Applicative()

let test (a : option<int>) (b : option<int>) =
    app {
        let! a = a
        and! b = b
        let x = b * b + a
        return a * b + x
    }
```
Please feel free to reopen if needed.

**Comment by Zaid-Ajaj** [comment]
Thanks @ncave for the follow up and apologies that I didn't actually test the feature before opening the issue to verify that it is already supported!
