### ISSUE TITLE
REPL crashing Firefox 52.4.0 (32-bit)

### ISSUE THREAD

**Issue by kellerd** [fable-compiler/Fable#1206]
### Description

Opening fable.io/repl crashes Firefox ESR 52.4.0 (32-bit).
Message in the JS window of fable reads Loading... before crash. 

### Repro code

The fable.io/repl sample

let FSharp, JS = "F#", "JS"
let ♥ x y = x + " loves " + y

JS
|> ♥ FSharp
|> printfn "FABLE: %s"

### Related information

* Fable version (`dotnet fable --version`): Fable v1.2.0, FCS v14.0.2, Babel v6.26.0
* Operating system: Windows
Firefox ESR 52.4.0 (32-bit)

Chrome Reports these errors:
bundle.min.js:1 Cannot find type System.ValueTuple`1
bundle.min.js:1 Cannot find type System.ValueTuple`2
bundle.min.js:1 Cannot find type System.ValueTuple`3
bundle.min.js:1 Cannot find type System.ValueTuple`4
bundle.min.js:1 Cannot find type System.ValueTuple`5
bundle.min.js:1 Cannot find type System.ValueTuple`6
bundle.min.js:1 Cannot find type System.ValueTuple`7
bundle.min.js:1 Cannot find type System.ValueTuple`8

**Comment by ncave** [comment]
@kellerd Unfortunately yes, it does crash the browser. Hopefully Mozilla can fix that issue, as it works fine in standard (non-ESR) versions (v56.0.2, and other versions before that, both 32-bit and 64-bit, are ok).

**Comment by kellerd** [comment]
Closing as there isn't much to do, and you've already done quite a bit of Firefox regression testing.
