### ISSUE TITLE
Compilation error: FABLE: Cannot resolve System.Globalization.Calendar.GetWeekOfYear

### ISSUE THREAD

**Issue by stan-kroon** [fable-compiler/Fable#2243]
### Description

I'm trying to get the week number of a date using the System.Globalization.Calendar.GetWeekOfYear function (https://docs.microsoft.com/en-us/dotnet/api/system.globalization.calendar.getweekofyear?view=netcore-3.1)
The code below does not compile using the fable-compiler (2.13.0) while it does compile using `dotnet build`
### Repro code
The following code causes the error in the REPL:

```
open System.Globalization
open System

CultureInfo.CurrentCulture.Calendar.GetWeekOfYear(DateTime(1,1,2020), CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Monday)
```

### Expected and actual results

Expected: returns integer corresponding to week number of specified date.
Actual: throws the following error:
`FABLE: Cannot resolve System.Globalization.CultureInfo.get_CurrentCulture`

### Related information

local fable-compiler version: 2.13.0
REPL fable-compiler version: 2.10.1
operating system: Windows 10 (error is reproducible in REPL)

**Comment by MangelMaxime** [comment]
Hello @stan-kroon,

Fable doesn't provide support for all the BCL API's and the "Globalization" API is one of them.

I don't think that support for it will be included in Fable.

**Comment by stan-kroon** [comment]
Thanks for your response Maxime, makes sense!

**Comment by alfonsogarciacaro** [comment]
Maybe related, there's a proposal to support `CultureInfo` #2126. It's not a priority at the moment, but of course anybody wanting to give it a try is more than welcome :)

**Comment by Zaid-Ajaj** [comment]
@stan-kroon Also related :wink: you can install [Fable.DateFunctions](https://github.com/Zaid-Ajaj/Fable.DateFunctions) (along with its dependency `date-fns`) and then calculate which week it is like this
```fs
open System
open Fable.DateFunctions

let now = DateTime.Now
let currentWeekNumber = now.DifferenceInCalendarWeeks(now.StartOfYear())
```
At least, I think this will work :smile:

**Comment by stan-kroon** [comment]
Thanks Zaid-Ajaj, that is exactly what I need!
